version: "3.7"

services:
  population_server: #container name
    build:
      context: ./api
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/api/entrypoint.sh']
    volumes:
      - ./api/:/usr/src/api
    ports: 
      - 5000:5000
    environment: 
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@population_db:5432/population_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@population_db:5432/population_test
      - SECRET_KEY=b52cfa53fc5bdc786f0c7b1765492641c019a87ebab52f5e
    depends_on: 
      - population_db

  population_client: #container name
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui/:/usr/src/app
      - '/usr/src/app/node_modules'
    ports:
      - 3005:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  population_db:
    build:
      context: ./api/project/db
      dockerfile: Dockerfile
    expose: 
      - 5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
